export type { PaginationMeta, PaginationHeader, ResponseMetadata, JsonPatchOperation } from './common';
export type {
  AuthorDto,
  GetAllAuthorsHttpRequest,
  GetAllAuthorsHttpResponse,
  GetAuthorByIdHttpRequest,
  GetAuthorByIdHttpResponse,
  ExistsAuthorHttpRequest,
  ExistsAuthorHttpResponse,
  ExistsAuthorHttpData,
  CheckAuthorNameUniquenessHttpRequest,
  CheckAuthorNameUniquenessHttpResponse,
  CheckAuthorNameUniquenessHttpData,
  CreateAuthorHttpRequest,
  CreateAuthorHttpResponse,
  UpsertAuthorHttpRequest,
  UpsertAuthorHttpResponse,
  UpdatePartialAuthorHttpRequest,
  DeleteAuthorHttpRequest,
} from './author';
export type {
  PaperDto,
  GetAllPapersOfAuthorHttpRequest,
  GetAllPapersOfAuthorHttpResponse,
  GetPaperOfAuthorByPaperIdHttpRequest,
  GetPaperOfAuthorByPaperIdHttpResponse,
  ExistsPaperOfAuthorHttpRequest,
  ExistsPaperOfAuthorHttpResponse,
  ExistsPaperOfAuthorHttpData,
  CheckPaperTitleUniquenessOfAuthorHttpRequest,
  CheckPaperTitleUniquenessOfAuthorHttpResponse,
  CheckPaperTitleUniquenessOfAuthorHttpData,
  AddPaperToAuthorHttpRequest,
  AddPaperToAuthorHttpResponse,
  UpsertPaperOfAuthorHttpRequest,
  UpsertPaperOfAuthorHttpResponse,
  UpdatePartialPaperOfAuthorHttpRequest,
  RemovePaperFromAuthorHttpRequest,
} from './paper';
export type {
  AwardDto,
  GetAllAwardsOfAuthorHttpRequest,
  GetAllAwardsOfAuthorHttpResponse,
  GetAwardOfAuthorByAwardIdHttpRequest,
  GetAwardOfAuthorByAwardIdHttpResponse,
  ExistsAwardOfAuthorHttpRequest,
  ExistsAwardOfAuthorHttpResponse,
  ExistsAwardOfAuthorHttpData,
  CheckAwardTitleUniquenessOfAuthorHttpRequest,
  CheckAwardTitleUniquenessOfAuthorHttpResponse,
  CheckAwardTitleUniquenessOfAuthorHttpData,
  AddAwardToAuthorHttpRequest,
  AddAwardToAuthorHttpResponse,
  UpsertAwardOfAuthorHttpRequest,
  UpsertAwardOfAuthorHttpResponse,
  UpdatePartialAwardOfAuthorHttpRequest,
  RemoveAwardFromAuthorHttpRequest,
} from './award';
export type {
  AffiliationDto,
  GetAllAffiliationsOfAuthorHttpRequest,
  GetAllAffiliationsOfAuthorHttpResponse,
  GetAffiliationOfAuthorByAffiliationIdHttpRequest,
  GetAffiliationOfAuthorByAffiliationIdHttpResponse,
  ExistsAffiliationOfAuthorHttpRequest,
  ExistsAffiliationOfAuthorHttpResponse,
  ExistsAffiliationOfAuthorHttpData,
  CheckAffiliationNameUniquenessOfAuthorHttpRequest,
  CheckAffiliationNameUniquenessOfAuthorHttpResponse,
  CheckAffiliationNameUniquenessOfAuthorHttpData,
  AddAffiliationToAuthorHttpRequest,
  AddAffiliationToAuthorHttpResponse,
  UpsertAffiliationOfAuthorHttpRequest,
  UpsertAffiliationOfAuthorHttpResponse,
  UpdatePartialAffiliationOfAuthorHttpRequest,
  RemoveAffiliationFromAuthorHttpRequest,
} from './affiliation';
