export type {
  LiteraryGenreDto,
  GetAllLiteraryGenresHttpRequest,
  GetAllLiteraryGenresHttpResponse,
  GetLiteraryGenreByIdHttpRequest,
  GetLiteraryGenreByIdHttpResponse,
  ExistsLiteraryGenreHttpRequest,
  ExistsLiteraryGenreHttpResponse,
  ExistsLiteraryGenreHttpData,
  CheckLiteraryGenreNameUniquenessHttpRequest,
  CheckLiteraryGenreNameUniquenessHttpResponse,
  CheckLiteraryGenreNameUniquenessHttpData,
} from './literary-genre';
export type {
  PublisherDto,
  GetAllPublishersHttpRequest,
  GetAllPublishersHttpResponse,
  GetPublisherByIdHttpRequest,
  GetPublisherByIdHttpResponse,
  ExistsPublisherHttpRequest,
  ExistsPublisherHttpResponse,
  ExistsPublisherHttpData,
  CheckPublisherNameUniquenessHttpRequest,
  CheckPublisherNameUniquenessHttpResponse,
  CheckPublisherNameUniquenessHttpData,
} from './publisher';
